In [114]:

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier

In [84]:
df = pd.read_csv('bdastudents.csv', sep=';')
df

school sex  age address  famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0        GP   F   18       U        1       A     4     4   at_home   teacher   
1        GP   F   17       U        1       T     1     1   at_home     other   
2        GP   F   15       U        0       T     1     1   at_home     other   
3        GP   F   15       U        1       T     4     2    health  services   
4        GP   F   16       U        1       T     3     3     other     other   
...     ...  ..  ...     ...      ...     ...   ...   ...       ...       ...   
1039     MS   F   19       R        1       T     2     3  services     other   
1040     MS   F   18       U        0       T     3     1   teacher  services   
1041     MS   F   18       U        1       T     1     1     other     other   
1042     MS   M   17       U        0       T     3     1  services  services   
1043     MS   M   18       R        0       T     3     2  services     other   

      ... famrel freetime  goout  Dalc  Walc  health  absences  G1  G2  G3  
0     ...      4        3      4     1     1       3         6   0   0   0  
1     ...      5        3      3     1     1       3         4   0   0   0  
2     ...      4        3      2     2     3       3        10   1   1   1  
3     ...      3        2      2     1     1       5         2   2   1   2  
4     ...      4        3      2     1     2       5         4   0   1   1  
...   ...    ...      ...    ...   ...   ...     ...       ...  ..  ..  ..  
1039  ...      5        4      2     1     2       5         4   1   1   1  
1040  ...      4        3      4     1     1       1         4   2   2   2  
1041  ...      1        1      1     1     1       5         6   1   1   1  
1042  ...      2        4      5     3     4       2         6   1   1   1  
1043  ...      4        4      1     3     4       5         4   1   1   1  

[1044 rows x 32 columns]

1. Scikit-learn utilizza un array numpy per effettuare le proprie predizioni. Gli elementi
dell’array numpy devono essere di tipo numerico. Creare un dataset chiamato “numeric” che
contiene solo le features numeriche.
Creare poi un nuovo dataset “reduced” dall’originale con le colonne G1 e G2 e un dataset
“lessReduced” togliendo da numeric unicamente le colonne G1 e G2(punti 1).


In [85]:
numerical_cols = []
for col in df.columns:
    if(df[col].dtype == 'int64'):
        numerical_cols.append(col)

numeric = df[numerical_cols]
numeric

age  famsize  Medu  Fedu  traveltime  studytime  failures  schoolsup  \
0      18        1     4     4           2          2         0          1   
1      17        1     1     1           1          2         0          0   
2      15        0     1     1           1          2         3          1   
3      15        1     4     2           1          3         0          0   
4      16        1     3     3           1          2         0          0   
...   ...      ...   ...   ...         ...        ...       ...        ...   
1039   19        1     2     3           1          3         1          0   
1040   18        0     3     1           1          2         0          0   
1041   18        1     1     1           2          2         0          0   
1042   17        0     3     1           2          1         0          0   
1043   18        0     3     2           3          1         0          0   

      famsup  paid  ...  famrel  freetime  goout  Dalc  Walc  health  \
0          0     0  ...       4         3      4     1     1       3   
1          1     0  ...       5         3      3     1     1       3   
2          0     1  ...       4         3      2     2     3       3   
3          1     1  ...       3         2      2     1     1       5   
4          1     1  ...       4         3      2     1     2       5   
...      ...   ...  ...     ...       ...    ...   ...   ...     ...   
1039       0     0  ...       5         4      2     1     2       5   
1040       1     0  ...       4         3      4     1     1       1   
1041       0     0  ...       1         1      1     1     1       5   
1042       0     0  ...       2         4      5     3     4       2   
1043       0     0  ...       4         4      1     3     4       5   

      absences  G1  G2  G3  
0            6   0   0   0  
1            4   0   0   0  
2           10   1   1   1  
3            2   2   1   2  
4            4   0   1   1  
...        ...  ..  ..  ..  
1039         4   1   1   1  
1040         4   2   2   2  
1041         6   1   1   1  
1042         6   1   1   1  
1043         4   1   1   1  

[1044 rows x 24 columns]

In [86]:
reduced = df[['G1', 'G2']]
reduced

G1  G2
0      0   0
1      0   0
2      1   1
3      2   1
4      0   1
...   ..  ..
1039   1   1
1040   2   2
1041   1   1
1042   1   1
1043   1   1

[1044 rows x 2 columns]

In [87]:
less_reduced = numeric.drop(['G1', 'G2'], axis=1)
less_reduced

age  famsize  Medu  Fedu  traveltime  studytime  failures  schoolsup  \
0      18        1     4     4           2          2         0          1   
1      17        1     1     1           1          2         0          0   
2      15        0     1     1           1          2         3          1   
3      15        1     4     2           1          3         0          0   
4      16        1     3     3           1          2         0          0   
...   ...      ...   ...   ...         ...        ...       ...        ...   
1039   19        1     2     3           1          3         1          0   
1040   18        0     3     1           1          2         0          0   
1041   18        1     1     1           2          2         0          0   
1042   17        0     3     1           2          1         0          0   
1043   18        0     3     2           3          1         0          0   

      famsup  paid  ...  internet  romantic  famrel  freetime  goout  Dalc  \
0          0     0  ...         0         0       4         3      4     1   
1          1     0  ...         1         0       5         3      3     1   
2          0     1  ...         1         0       4         3      2     2   
3          1     1  ...         1         1       3         2      2     1   
4          1     1  ...         0         0       4         3      2     1   
...      ...   ...  ...       ...       ...     ...       ...    ...   ...   
1039       0     0  ...         1         0       5         4      2     1   
1040       1     0  ...         1         0       4         3      4     1   
1041       0     0  ...         0         0       1         1      1     1   
1042       0     0  ...         1         0       2         4      5     3   
1043       0     0  ...         1         0       4         4      1     3   

      Walc  health  absences  G3  
0        1       3         6   0  
1        1       3         4   0  
2        3       3        10   1  
3        1       5         2   2  
4        2       5         4   1  
...    ...     ...       ...  ..  
1039     2       5         4   1  
1040     1       1         4   2  
1041     1       5         6   1  
1042     4       2         6   1  
1043     4       5         4   1  

[1044 rows x 22 columns]

2. Si vuole predire G3 sulla base degli altri attributi presenti nel dataset. Dividere i dataset
numeric, lessReduced e reduced in modo che 2/3 degli elementi siano contenuti in un nuovo
dataset “train” e 1/3 nel dataset “test” (punti 2).


In [88]:
X_num = numeric.drop(['G3'], axis=1)
y = numeric['G3']

X_num_train, X_num_test, y_num_train, y_num_test = train_test_split(X_num, y, test_size=0.33, random_state=42)

X=less_reduced.drop(['G3'], axis=1)
X_less_train, X_less_test, _, _ = train_test_split(X, y, test_size=0.33, random_state=42)

X_red_train, X_red_test, _, _ = train_test_split(reduced, y, test_size=0.33, random_state=42)

In [89]:
import warnings
warnings.filterwarnings('ignore')

lr = LogisticRegression()
lr.fit(X_num_train, y_num_train)

y_pred = lr.predict(X_num_test)
acc_num = accuracy_score(y_num_test, y_pred)
print(f'Numeric: {acc_num}')
print(confusion_matrix(y_num_test, y_pred))

lr.fit(X_less_train, y_num_train)
y_pred = lr.predict(X_less_test)
acc_less = accuracy_score(y_num_test, y_pred)
print(f'Less Reduced: {acc_less}')
print(confusion_matrix(y_num_test, y_pred))

lr.fit(X_red_train, y_num_train)
y_pred = lr.predict(X_red_test)
acc_red = accuracy_score(y_num_test, y_pred)
print(f'Reduced: {acc_red}')
print(confusion_matrix(y_num_test, y_pred))


Numeric: 0.9014492753623189
[[ 13  17   0]
 [  1 245   0]
 [  0  16  53]]
Less Reduced: 0.7072463768115942
[[  0  28   2]
 [  2 234  10]
 [  0  59  10]]
Reduced: 0.9101449275362319
[[ 16  14   0]
 [  1 245   0]
 [  0  16  53]]


3. Che valore di accuratezza si ottiene con un 10 Fold cross validation e il modello basato su
Decision Tree ________________
E’ più affidabile la valutazione fatta con la cross validation o quella fatta con una suddivisione
arbitraria del dataset in due parti, training set e test set? Per quale motivo? (punti 2).


In [90]:
cross = cross_val_score(DecisionTreeClassifier(), X_num, y, cv=10)
print(f'Cross val: {cross}, mean: {np.mean(cross)}')

Cross val: [0.88571429 0.9047619  0.8952381  0.82857143 0.84615385 0.85576923
 0.875      0.77884615 0.77884615 0.84615385], mean: 0.8495054945054946


4. Considerare il dataset numeric. Considerare l’intervallo di valori assunto dall’attributo age e
dividerlo in tre parti. Associare a ogni istanza il valore 0,1,2 a seconda del fatto che l’età sia nel
primo, nel secondo o nel terzo intervallo. Eliminare l’attributo age originale, non discretizzato e
calcolare l’accuratezza con il metodo 10 cross fold validation.
___________________________________________________________________________________
Trasformare la feature discretizzata in 3 feature booleane, una per ogni valore discretizzato. Il
valore assegnato sarà 1 nella colonna che rappresenta il valore in esame. 0 nelle altre colonne.
Calcolare l’accuratezza con il metodo 10 cross fold validation (punti 4).
_______________________________________________________

In [91]:
numeric['age'] = pd.cut(numeric['age'], bins=3, labels=[0, 1, 2])
numeric

age  famsize  Medu  Fedu  traveltime  studytime  failures  schoolsup  \
0      1        1     4     4           2          2         0          1   
1      0        1     1     1           1          2         0          0   
2      0        0     1     1           1          2         3          1   
3      0        1     4     2           1          3         0          0   
4      0        1     3     3           1          2         0          0   
...   ..      ...   ...   ...         ...        ...       ...        ...   
1039   1        1     2     3           1          3         1          0   
1040   1        0     3     1           1          2         0          0   
1041   1        1     1     1           2          2         0          0   
1042   0        0     3     1           2          1         0          0   
1043   1        0     3     2           3          1         0          0   

      famsup  paid  ...  famrel  freetime  goout  Dalc  Walc  health  \
0          0     0  ...       4         3      4     1     1       3   
1          1     0  ...       5         3      3     1     1       3   
2          0     1  ...       4         3      2     2     3       3   
3          1     1  ...       3         2      2     1     1       5   
4          1     1  ...       4         3      2     1     2       5   
...      ...   ...  ...     ...       ...    ...   ...   ...     ...   
1039       0     0  ...       5         4      2     1     2       5   
1040       1     0  ...       4         3      4     1     1       1   
1041       0     0  ...       1         1      1     1     1       5   
1042       0     0  ...       2         4      5     3     4       2   
1043       0     0  ...       4         4      1     3     4       5   

      absences  G1  G2  G3  
0            6   0   0   0  
1            4   0   0   0  
2           10   1   1   1  
3            2   2   1   2  
4            4   0   1   1  
...        ...  ..  ..  ..  
1039         4   1   1   1  
1040         4   2   2   2  
1041         6   1   1   1  
1042         6   1   1   1  
1043         4   1   1   1  

[1044 rows x 24 columns]

In [92]:
X_num = numeric.drop(['G3'], axis=1)
cross = cross_val_score(DecisionTreeClassifier(), X_num, y, cv=10)
print(f'Cross val: {cross}, mean: {np.mean(cross)}')

Cross val: [0.87619048 0.8952381  0.85714286 0.83809524 0.80769231 0.85576923
 0.90384615 0.78846154 0.78846154 0.86538462], mean: 0.8476282051282051


Trasformare la feature discretizzata in 3 feature booleane, una per ogni valore discretizzato. Il
valore assegnato sarà 1 nella colonna che rappresenta il valore in esame. 0 nelle altre colonne.
Calcolare l’accuratezza con il metodo 10 cross fold validation (punti 4).


In [93]:
numeric = pd.get_dummies(numeric, columns=['age'], dtype='int64')
numeric

famsize  Medu  Fedu  traveltime  studytime  failures  schoolsup  famsup  \
0           1     4     4           2          2         0          1       0   
1           1     1     1           1          2         0          0       1   
2           0     1     1           1          2         3          1       0   
3           1     4     2           1          3         0          0       1   
4           1     3     3           1          2         0          0       1   
...       ...   ...   ...         ...        ...       ...        ...     ...   
1039        1     2     3           1          3         1          0       0   
1040        0     3     1           1          2         0          0       1   
1041        1     1     1           2          2         0          0       0   
1042        0     3     1           2          1         0          0       0   
1043        0     3     2           3          1         0          0       0   

      paid  nursery  ...  Dalc  Walc  health  absences  G1  G2  G3  age_0  \
0        0        1  ...     1     1       3         6   0   0   0      0   
1        0        0  ...     1     1       3         4   0   0   0      1   
2        1        1  ...     2     3       3        10   1   1   1      1   
3        1        1  ...     1     1       5         2   2   1   2      1   
4        1        1  ...     1     2       5         4   0   1   1      1   
...    ...      ...  ...   ...   ...     ...       ...  ..  ..  ..    ...   
1039     0        0  ...     1     2       5         4   1   1   1      0   
1040     0        1  ...     1     1       1         4   2   2   2      0   
1041     0        1  ...     1     1       5         6   1   1   1      0   
1042     0        0  ...     3     4       2         6   1   1   1      1   
1043     0        0  ...     3     4       5         4   1   1   1      0   

      age_1  age_2  
0         1      0  
1         0      0  
2         0      0  
3         0      0  
4         0      0  
...     ...    ...  
1039      1      0  
1040      1      0  
1041      1      0  
1042      0      0  
1043      1      0  

[1044 rows x 26 columns]

In [94]:
X_num = numeric.drop(['G3'], axis=1)
cross = cross_val_score(DecisionTreeClassifier(), X_num, y, cv=10)
print(f'Cross val: {cross}, mean: {np.mean(cross)}')

Cross val: [0.87619048 0.9047619  0.85714286 0.82857143 0.80769231 0.86538462
 0.88461538 0.79807692 0.79807692 0.81730769], mean: 0.8437820512820513


5. Aggiungere al dataset “numeric” gli attributi Mjob e Fjob il cui valore categorico deve essere
mappato utilizzando una formula di conversione a scelta. Confrontare il risultato ottenuto con
quelli ottenuti in precedenza (punti 4).

In [100]:
numeric['Mjob'] = df['Mjob']
numeric['Fjob'] = df['Fjob']
le = LabelEncoder()
numeric['Mjob'] = le.fit_transform(numeric['Mjob'])
numeric['Fjob'] = le.fit_transform(numeric['Fjob'])
numeric

famsize  Medu  Fedu  traveltime  studytime  failures  schoolsup  famsup  \
0           1     4     4           2          2         0          1       0   
1           1     1     1           1          2         0          0       1   
2           0     1     1           1          2         3          1       0   
3           1     4     2           1          3         0          0       1   
4           1     3     3           1          2         0          0       1   
...       ...   ...   ...         ...        ...       ...        ...     ...   
1039        1     2     3           1          3         1          0       0   
1040        0     3     1           1          2         0          0       1   
1041        1     1     1           2          2         0          0       0   
1042        0     3     1           2          1         0          0       0   
1043        0     3     2           3          1         0          0       0   

      paid  nursery  ...  health  absences  G1  G2  G3  age_0  age_1  age_2  \
0        0        1  ...       3         6   0   0   0      0      1      0   
1        0        0  ...       3         4   0   0   0      1      0      0   
2        1        1  ...       3        10   1   1   1      1      0      0   
3        1        1  ...       5         2   2   1   2      1      0      0   
4        1        1  ...       5         4   0   1   1      1      0      0   
...    ...      ...  ...     ...       ...  ..  ..  ..    ...    ...    ...   
1039     0        0  ...       5         4   1   1   1      0      1      0   
1040     0        1  ...       1         4   2   2   2      0      1      0   
1041     0        1  ...       5         6   1   1   1      0      1      0   
1042     0        0  ...       2         6   1   1   1      1      0      0   
1043     0        0  ...       5         4   1   1   1      0      1      0   

      Mjob  Fjob  
0        0     4  
1        0     2  
2        0     2  
3        1     3  
4        2     2  
...    ...   ...  
1039     3     2  
1040     4     3  
1041     2     2  
1042     3     3  
1043     3     2  

[1044 rows x 28 columns]

In [101]:
X_num = numeric.drop(['G3'], axis=1)
cross = cross_val_score(DecisionTreeClassifier(), X_num, y, cv=10)
print(f'Cross val: {cross}, mean: {np.mean(cross)}')

Cross val: [0.8952381  0.8952381  0.8        0.85714286 0.83653846 0.85576923
 0.89423077 0.76923077 0.79807692 0.83653846], mean: 0.8438003663003663


6. Partendo dal dataset originale, costruire due dataset contenenti solo le feature numeriche.
Uno che rappresenti la scuola GP e l’altro la scuola MS. Costruire due modelli di predizione
utilizzando il decision tree. Uno per gli studenti GP e l’altro per gli studenti MS. Allenare
entrambi i modelli utilizzando 2/3 delle rispettive istanze come training.
Fondere i test in un unico file.
Verificare l’accuratezza ottenuta dal test in entrambi i modelli. Quale funziona meglio?
(punti 3)

In [102]:
df_MS = df[df['school']== 'MS'][numerical_cols]
df_MS

age  famsize  Medu  Fedu  traveltime  studytime  failures  schoolsup  \
349    18        1     3     2           2          1         1          0   
350    19        1     1     1           3          2         3          0   
351    17        1     3     3           2          2         0          0   
352    18        0     1     3           1          1         1          0   
353    19        1     1     1           3          1         1          0   
...   ...      ...   ...   ...         ...        ...       ...        ...   
1039   19        1     2     3           1          3         1          0   
1040   18        0     3     1           1          2         0          0   
1041   18        1     1     1           2          2         0          0   
1042   17        0     3     1           2          1         0          0   
1043   18        0     3     2           3          1         0          0   

      famsup  paid  ...  famrel  freetime  goout  Dalc  Walc  health  \
349        1     0  ...       2         5      5     5     5       5   
350        0     0  ...       5         4      4     3     3       2   
351        1     1  ...       4         5      4     2     3       3   
352        0     0  ...       4         3      3     2     3       3   
353        1     0  ...       4         4      4     3     3       5   
...      ...   ...  ...     ...       ...    ...   ...   ...     ...   
1039       0     0  ...       5         4      2     1     2       5   
1040       1     0  ...       4         3      4     1     1       1   
1041       0     0  ...       1         1      1     1     1       5   
1042       0     0  ...       2         4      5     3     4       2   
1043       0     0  ...       4         4      1     3     4       5   

      absences  G1  G2  G3  
349         10   1   1   1  
350          8   1   1   1  
351          2   1   1   1  
352          7   1   1   1  
353          4   1   1   1  
...        ...  ..  ..  ..  
1039         4   1   1   1  
1040         4   2   2   2  
1041         6   1   1   1  
1042         6   1   1   1  
1043         4   1   1   1  

[272 rows x 24 columns]

In [103]:
df_GP = df[df['school']== 'GP'][numerical_cols]
df_GP

age  famsize  Medu  Fedu  traveltime  studytime  failures  schoolsup  \
0     18        1     4     4           2          2         0          1   
1     17        1     1     1           1          2         0          0   
2     15        0     1     1           1          2         3          1   
3     15        1     4     2           1          3         0          0   
4     16        1     3     3           1          2         0          0   
..   ...      ...   ...   ...         ...        ...       ...        ...   
813   18        1     2     3           1          1         0          0   
814   19        1     2     1           1          1         0          0   
815   18        0     2     2           2          2         0          0   
816   20        1     1     0           2          1         1          1   
817   18        1     3     2           1          2         0          0   

     famsup  paid  ...  famrel  freetime  goout  Dalc  Walc  health  absences  \
0         0     0  ...       4         3      4     1     1       3         6   
1         1     0  ...       5         3      3     1     1       3         4   
2         0     1  ...       4         3      2     2     3       3        10   
3         1     1  ...       3         2      2     1     1       5         2   
4         1     1  ...       4         3      2     1     2       5         4   
..      ...   ...  ...     ...       ...    ...   ...   ...     ...       ...   
813       0     0  ...       3         1      3     4     5       4        13   
814       0     0  ...       5         3      4     1     4       4        10   
815       1     0  ...       4         1      4     1     3       4        10   
816       0     0  ...       5         3      1     1     1       5         5   
817       1     0  ...       3         1      2     1     2       1         4   

     G1  G2  G3  
0     0   0   0  
1     0   0   0  
2     1   1   1  
3     2   1   2  
4     0   1   1  
..   ..  ..  ..  
813   1   1   1  
814   1   1   1  
815   1   2   2  
816   1   1   1  
817   1   1   1  

[772 rows x 24 columns]

In [112]:
XMS = df_MS.drop(['G3'], axis=1)
yMS = df_MS['G3']
XMS_train, XMS_test, yMS_train, yMS_test =train_test_split(XMS, yMS, test_size=0.33, random_state=42)

XGP = df_GP.drop(['G3'], axis=1)
yGP = df_GP['G3']
XGP_train, XGP_test, yGP_train, yGP_test =train_test_split(XGP, yGP, test_size=0.33, random_state=42)

dt1 =DecisionTreeClassifier()
dt1.fit(XMS_train, yMS_train)

dt2 = DecisionTreeClassifier()
dt2.fit(XGP_train, yGP_train)

X_test = pd.concat([XMS_test, XGP_test])
y_test = pd.concat([yMS_test, yGP_test])
y_test

379    1
888    1
851    2
899    1
968    1
      ..
29     1
406    1
264    0
750    1
578    2
Name: G3, Length: 345, dtype: int64

In [113]:

y_pred1 = dt1.predict(X_test)
y_pred2 = dt2.predict(X_test)

print(f'MS: {accuracy_score(y_test, y_pred1)}, GP: {accuracy_score(y_test, y_pred2)}')

MS: 0.8521739130434782, GP: 0.8318840579710145


# 7
Utilizzare un algoritmo di regressione da applicarsi al dataset del punto 1 per predire “G3”.
Arrotondare i valori ottenuti all’intero. Confrontare i risultati ottenuti con quelli ottenuti in
precedenza (punti 3).


In [119]:
lin_reg = LinearRegression()

numeric = df[numerical_cols]

X_num = numeric.drop(['G3'], axis=1)
y = numeric['G3']

X_num_train, X_num_test, y_num_train, y_num_test = train_test_split(X_num, y, test_size=0.33, random_state=42)

lin_reg.fit(X_num_train, y_num_train)
y_pred = lin_reg.predict(X_num_test)
y_pred_round  = np.round(y_pred)
acc_num = accuracy_score(y_num_test, y_pred_round)
print(f'Numeric: {acc_num}')

confronto = pd.DataFrame({
    'Reale': y_num_test,
    'Predizione_Grezza': y_pred,
    'Predizione_Arrotondata': y_pred_round
})
confronto

Numeric: 0.9101449275362319


Reale  Predizione_Grezza  Predizione_Arrotondata
971      1           0.981561                     1.0
280      1           1.004378                     1.0
536      1           1.016974                     1.0
824      1           1.104700                     1.0
644      1           1.117506                     1.0
..     ...                ...                     ...
914      0           1.059008                     1.0
620      1           1.081138                     1.0
849      1           0.972713                     1.0
177      0           0.164229                     0.0
998      0           0.119505                     0.0

[345 rows x 3 columns]