# Numpy


In [2]:
import numpy as np

#Matrice Identità
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
## Reshape

In [8]:
arr = np.empty((4, 3))
for i in range(4):
    arr[i] = i
arr

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [9]:
arr.reshape((-1, 2))

array([[0., 0.],
       [0., 1.],
       [1., 1.],
       [2., 2.],
       [2., 3.],
       [3., 3.]])

## Joining and splittin

In [13]:
x = np.array([1,2,3])
y = np.array([[4,5,6],[7,8,9]])
x #y

array([1, 2, 3])

Per concatenare le righe

In [15]:
np.vstack([x,y])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Per concatenare le colonne

In [16]:
np.hstack([y,y])

array([[4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

Splitting

In [21]:
z, k = np.split(y,[1]) #1 è il numero di righe da mettere le primo split
# con axis = 1 splitto per le colonne
z

array([[4],
       [7]])