In [1]:
import numpy as np
import pandas as pd

- In Data Analysis, a significant amount of time is spent on data preparation: loading, cleaning, transforming, and rearranging.
    - Such tasks are often reported to take up 80% or more of an analyst’s time.
- Pandas provides you with a high-level, flexible, and fast set of tools to enable you to manipulate data into the right form.
- Much of the design and implementation of pandas has been driven by the needs of real-world applications.

## Handling Missing Data
- Missing data occurs commonly in many data analysis applications.
    - All of the descriptive statistics on pandas objects exclude missing data by default.
- The missing data is represented in pandas with the floating-point value NaN (Not a Number).
    - We call this a sentinel value that can be easily detected.

- In pandas, missing data is also referred  as  NA (i.e., "not available").
- In statistics applications, NA means
    - data that does not exist
    - data that exists but was not observed

- When cleaning up data for analysis, it is often important to do analysis on the missing data itself to identify data
collection problems or potential biases in the data caused by missing data.
- The built-in Python None value is also treated as NA

In [2]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])

In [3]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [4]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [5]:
string_data[0] = None

In [6]:
string_data

0         None
1    artichoke
2          NaN
3      avocado
dtype: object

In [7]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

### Filtering Out Missing Data

- dropna: Remove missing values.

In [8]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [9]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [10]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [11]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [12]:
data.notnull()

0     True
1    False
2     True
3    False
4     True
dtype: bool

In [13]:
#dropna is equivalent to
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

- dropna in Dataframe

In [14]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [15]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [16]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [17]:
cleaned = data.dropna(axis=1)

In [18]:
cleaned

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [19]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

- Passing how='all' will only drop rows that are all NA

In [20]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [21]:
data.dropna(how='any')    # default

0    1    2
0  1.0  6.5  3.0

- if you want to keep only rows containing a certain number of observations.

In [22]:
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan

In [23]:
df

0         1         2
0 -0.731811       NaN       NaN
1  0.362128       NaN       NaN
2 -0.253550       NaN  1.283726
3 -0.516625       NaN  0.818630
4  0.498982 -0.061024  0.309294
5  0.871741  0.678644 -0.697641
6  1.480748 -1.428570 -1.118614

In [24]:
df.dropna(thresh=2)

0         1         2
2 -0.253550       NaN  1.283726
3 -0.516625       NaN  0.818630
4  0.498982 -0.061024  0.309294
5  0.871741  0.678644 -0.697641
6  1.480748 -1.428570 -1.118614

### Filling In Missing Data

- *fillna*: Fill NA/NaN values using the specified method

In [25]:
df

0         1         2
0 -0.731811       NaN       NaN
1  0.362128       NaN       NaN
2 -0.253550       NaN  1.283726
3 -0.516625       NaN  0.818630
4  0.498982 -0.061024  0.309294
5  0.871741  0.678644 -0.697641
6  1.480748 -1.428570 -1.118614

In [73]:
df.fillna(42)

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [27]:
df

0         1         2
0 -0.731811       NaN       NaN
1  0.362128       NaN       NaN
2 -0.253550       NaN  1.283726
3 -0.516625       NaN  0.818630
4  0.498982 -0.061024  0.309294
5  0.871741  0.678644 -0.697641
6  1.480748 -1.428570 -1.118614

In [28]:
#if the value to fill in depends on the column
df.fillna({1: 0.5, 2: 0})

0         1         2
0 -0.731811  0.500000  0.000000
1  0.362128  0.500000  0.000000
2 -0.253550  0.500000  1.283726
3 -0.516625  0.500000  0.818630
4  0.498982 -0.061024  0.309294
5  0.871741  0.678644 -0.697641
6  1.480748 -1.428570 -1.118614

In [29]:
df

0         1         2
0 -0.731811       NaN       NaN
1  0.362128       NaN       NaN
2 -0.253550       NaN  1.283726
3 -0.516625       NaN  0.818630
4  0.498982 -0.061024  0.309294
5  0.871741  0.678644 -0.697641
6  1.480748 -1.428570 -1.118614

In [30]:
df.fillna(0, inplace=True)

In [31]:
df

0         1         2
0 -0.731811  0.000000  0.000000
1  0.362128  0.000000  0.000000
2 -0.253550  0.000000  1.283726
3 -0.516625  0.000000  0.818630
4  0.498982 -0.061024  0.309294
5  0.871741  0.678644 -0.697641
6  1.480748 -1.428570 -1.118614

- computing a value

In [32]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan
df

0         1         2
0  0.464930  1.291267 -0.619076
1  0.123932  0.684288  0.478277
2 -1.581733       NaN  0.584195
3 -1.127898       NaN -0.461139
4  0.303207       NaN       NaN
5  0.674607       NaN       NaN

In [33]:
df.fillna(method='ffill')

/var/folders/d5/jd8cs2ds0lq81wp6tr68x7800000gn/T/ipykernel_76320/253117906.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')


0         1         2
0  0.464930  1.291267 -0.619076
1  0.123932  0.684288  0.478277
2 -1.581733  0.684288  0.584195
3 -1.127898  0.684288 -0.461139
4  0.303207  0.684288 -0.461139
5  0.674607  0.684288 -0.461139

In [34]:
#limit for forward and backward filling, maximum number of consecutive periods to fill
df.fillna(method='ffill', limit=2)

/var/folders/d5/jd8cs2ds0lq81wp6tr68x7800000gn/T/ipykernel_76320/2930444409.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', limit=2)


0         1         2
0  0.464930  1.291267 -0.619076
1  0.123932  0.684288  0.478277
2 -1.581733  0.684288  0.584195
3 -1.127898  0.684288 -0.461139
4  0.303207       NaN -0.461139
5  0.674607       NaN -0.461139

In [35]:
#we can use other functions
df.fillna(df.mean())

0         1         2
0  0.464930  1.291267 -0.619076
1  0.123932  0.684288  0.478277
2 -1.581733  0.987777  0.584195
3 -1.127898  0.987777 -0.461139
4  0.303207  0.987777 -0.004436
5  0.674607  0.987777 -0.004436

## Data Transformation


### Removing Duplicates

- *duplicated*
- drop_duplicated

In [36]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [37]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [38]:
# data['k1'].duplicated() is equivalent to
data.duplicated(['k1'])

0    False
1    False
2     True
3     True
4     True
5     True
6     True
dtype: bool

In [39]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [40]:
data['v1'] = range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [41]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### Transforming Data Using a Function or Mapping

- map: Map values of Series according to input correspondence.

In [42]:
data = pd.DataFrame({
    'device': ['iPhone', 'Galaxy S21', 'MacBook Pro', 'Pixel 6',
               'ThinkPad', 'iPad', 'Surface Pro', 'galaxy tab', 'Macbook air'],
    'price': [999, 799, 1299, 599, 1099, 799, 999, 649, 999]
})

1. passing dictionary

In [43]:
device_to_brand = {
    'iphone': 'Apple',
    'macbook pro': 'Apple',
    'macbook air': 'Apple',
    'ipad': 'Apple',
    'galaxy s21': 'Samsung',
    'galaxy tab': 'Samsung',
    'pixel 6': 'Google',
    'thinkpad': 'Lenovo',
    'surface pro': 'Microsoft'
}

In [44]:
data['brand'] = data['device'].str.lower().map(device_to_brand)
data

device  price      brand
0       iPhone    999      Apple
1   Galaxy S21    799    Samsung
2  MacBook Pro   1299      Apple
3      Pixel 6    599     Google
4     ThinkPad   1099     Lenovo
5         iPad    799      Apple
6  Surface Pro    999  Microsoft
7   galaxy tab    649    Samsung
8  Macbook air    999      Apple

### Replacing Values

- *replace*: Replace values given in *to_replace* with value.

In [45]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [46]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [47]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [48]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [49]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### Discretization and Binning

- *cut*: Bin values into discrete intervals. Use cut when you need to segment and sort data values into bins

In [50]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 59, 45, 41, 32]

In [51]:
bins = [18, 25, 35, 60, 100]

In [52]:
values = pd.cut(ages, bins)

In [53]:
values

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (35, 60], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [54]:
type(values)

pandas.core.arrays.categorical.Categorical

In [55]:
values.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 2, 2, 2, 1], dtype=int8)

In [56]:
values.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [57]:
values

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (35, 60], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [74]:
#These are the bin counts for the result of pandas.cut.
pd.value_counts(values)

/var/folders/d5/jd8cs2ds0lq81wp6tr68x7800000gn/T/ipykernel_76320/404124905.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(values)


(18, 25]     5
(35, 60]     4
(25, 35]     3
(60, 100]    0
Name: count, dtype: int64

In [75]:
#parenthesis means that the side is open,
#while the square bracket means it is closed (inclusive).
#You can change which side is closed by passing right=False:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [36, 61), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64, left]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [76]:
#You can also pass your own bin names by passing a list or array to the labels option:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
new_ages = pd.cut(ages, bins, labels=group_names)

In [77]:
new_ages.categories

Index(['Youth', 'YoungAdult', 'MiddleAged', 'Senior'], dtype='object')

In [62]:
pd.value_counts(new_ages)

/var/folders/d5/jd8cs2ds0lq81wp6tr68x7800000gn/T/ipykernel_76320/2120194990.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(new_ages)


Youth         5
MiddleAged    4
YoungAdult    3
Senior        0
Name: count, dtype: int64

In [63]:
# passing an integer, it will compute
#equal-length bins based on the minimum and maximum values in the data.
data = np.random.rand(20)
data

array([0.39931522, 0.61404617, 0.15549527, 0.73502079, 0.20712698,
       0.17186556, 0.18405705, 0.82029785, 0.67427589, 0.14832028,
       0.97663585, 0.69615744, 0.75343092, 0.24957373, 0.290308  ,
       0.30413186, 0.63587931, 0.01292317, 0.81354022, 0.96922038])

In [64]:
pd.cut(data, 13).codes

array([ 5,  8,  1,  9,  2,  2,  2, 10,  8,  1, 12,  9,  9,  3,  3,  3,  8,
        0, 10, 12], dtype=int8)

### Computing Indicator/Dummy Variables/ One Hot Encoding (OHE)
- This converts a categorical variable into a “dummy” or “indicator” matrix.

- If a column in a DataFrame has k distinct values,
    - you would derive a matrix or DataFrame with k columns containing all 1s and 0s.
- pandas has a get_dummies function for doing this

In [65]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                   'data1': range(6)})

In [66]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [67]:
pd.get_dummies(df['key'])

a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [78]:
pd.get_dummies(df['key'], dtype='int')

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [79]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [80]:
dummies

key_a  key_b  key_c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [71]:
df[['data1']]

data1
0      0
1      1
2      2
3      3
4      4
5      5

In [72]:
#to join the result in the original dataframe
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False